using Echo.Core.Configuration.Connection;

namespace Echo.Core.Configuration.User
{
    public sealed class AccountSettings
    {
        public string BareAddress { get; }
        public string? Resource { get; }
        public string? Nickname { get; }
        public string? Password { get; }
        public bool IsResourceAutoGenerated { get; }
        public ConnectionSettings ConnectionSettings { get; }

        public AccountSettings(string bareAddress, string? resource, string? nickname, string? password, bool isResourceAutoGenerated, ConnectionSettings connectionSettings)
        {
            BareAddress = bareAddress;
            Resource = resource;
            Nickname = nickname;
            Password = password;
            IsResourceAutoGenerated = isResourceAutoGenerated;
            ConnectionSettings = connectionSettings;
        }
    }
}